### ISSUE TITLE
Server not showing up in LAN games or public games. Can't connect either 'Got EOF on stdin'

### ISSUE THREAD

**Issue by jmgevers99** [nubing/factorio-headless#2]
I just installed this snap on my Ubuntu Server 18.04.
After starting the snap, the server does not appear in the server list.
I also cannot connect to it manually.
I am still quite a beginner on Linux, so it's probably my fault.
Any help is appreciated!

Log:
   0.000 2020-02-19 14:22:36; Factorio 0.18.8 (build 49568, linux64, headless)
   0.000 Operating system: Linux
   0.000 Program arguments: "/snap/factorio-headless/23/factorio/bin/x64/factorio" "--start-server-load-latest" 
   0.000 Read data path: /snap/factorio-headless/23/factorio/data
   0.000 Write data path: /var/snap/factorio-headless/common [215106/233703MB]
   0.000 Binaries path: /snap/factorio-headless/23/factorio/bin
   0.005 System info: [CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 8 cores, RAM: 7899 MB]
   0.006 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.006 Running in headless mode
   0.008 Loading mod core 0.0.0 (data.lua)
   0.059 Loading mod base 0.18.8 (data.lua)
   0.295 Loading mod base 0.18.8 (data-updates.lua)
   0.414 Checksum for core: 1768830303
   0.414 Checksum of base: 3815156147
   0.615 Prototype list checksum: 2313467567
   0.651 Info PlayerData.cpp:70: Local player-data.json unavailable
   0.651 Info PlayerData.cpp:75: Cloud player-data.json unavailable
   0.651 Info GlobalContext.cpp:1173: Resetting config.
   0.652 Factorio initialised
   0.653 Info ServerSynchronizer.cpp:28: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   0.653 Info ServerMultiplayerManager.cpp:773: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
   0.653 Info ServerMultiplayerManager.cpp:773: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
   0.653 Loading map /var/snap/factorio-headless/common/saves/_autosave1.zip: 1864181 bytes.
   0.667 Loading level.dat: 1759346 bytes.
   0.671 Info Scenario.cpp:187: Map version 0.17.52-0
   0.736 Warning ScenarioHistory.cpp:146: Scenario history is inconsistent: 0.51.51 (build 45814) >= 0.17.52 (build 45814).
   0.737 Loading script.dat: 133 bytes.
   0.739 Checksum for script /var/snap/factorio-headless/common/temp/currently-playing/control.lua: 4030479898
   0.740 Applying migration: Base Mod: 2019-06-28_Factorio_0.17.53.lua
   0.741 Applying migration: Base Mod: 2019-06-28_Factorio_0.17.54.lua
   0.742 Applying migration: Base Mod: 2019-08-05_Factorio_0.17.63.lua
   0.743 Applying migration: Base Mod: 2019-12-12_Factorio_0.18.00.lua
   0.744 Applying migration: Base Mod: 2020-01-27_Factorio_0.18.02.lua
   0.747 Checksum for script /var/snap/factorio-headless/common/temp/currently-playing/control.lua: 4030479898
   0.748 Info UDPSocket.cpp:27: Opening socket at (IP ADDR:({0.0.0.0:34197}))
   0.748 Hosting game at IP ADDR:({0.0.0.0:34197})
   0.748 Info ServerMultiplayerManager.cpp:773: updateTick(1564) changing state from(CreatingGame) to(InGame)
   0.748 Info UDPSocket.cpp:39: Opening socket for broadcast
   0.748 Error InterruptibleStdioStream.cpp:61: Got EOF on stdin; closing

**Comment by nubing** [comment]
I am getting that error also and I'm able to create games so I think that error can be ignored. Did you set username and token?

    snap set factorio-headless username="me"
    snap set factorio-headless token="token-from-factorio-account"
    snap restart factorio-headless

**Comment by jmgevers99** [comment]
Oh wow, I did not know you had to set that for a LAN game.
It's working now!
I did have 3 other questions though:
1. Is there anyway to select what savegame to use for the server?
2. Is there anyway to interact with the server once started, like sending server messages/commands.
3. Is there any documentation available where I can find the various commands for this snap?
For example I had no idea this command even existed: 'snap set factorio-headless username="me"'

Anyways, thanks very much already! 
I hope to hear from you soon

**Comment by nubing** [comment]
1. Saves are located in `/var/snap/factorio-headless/common/saves/`, replace them with save you want to run.

2. `snap set factorio-headless admins='["me"]'` https://wiki.factorio.com/Console#Multiplayer_commands

3. Sorry no docs yet. `snap set factorio-headless ...`
   
	name="Name of the game as it will appear in the game listing"
	description="Description of the game that will appear in the listing"
	tags='["game", "tags"]'
	max-players=0
	visibility-public=true
	visibility-lan=true
	username=""
	password=""
	token=""
	game-password=""
 	require-user-verification=true
  	max-upload-in-kilobytes-per-second=0
	minimum-latency-in-ticks=0
	ignore-player-limit-for-returning-players=false
	allow-commands="admins-only"
	autosave-interval=10
	autosave-slots=5
	afk-autokick-interval=0
	auto-pause=true
	only-admins-can-pause-the-game=true
	autosave-only-on-server=true
	non-blocking-saving=false
	admins='[]'
	port=""
	bind=""
	rcon-port=""
	rcon-password=""
